Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "chchinS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "part2_chchinS"
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y curl
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --node-ip 192.168.56.110
    kubectl apply -f /vagrant/yamls/.
  SHELL
end
