Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  # https://developer.hashicorp.com/vagrant/docs/multi-machine
  config.vm.define "maliewS" do |maliewS|

    # https://developer.hashicorp.com/vagrant/docs/networking/basic_usage
    maliewS.vm.hostname = "maliewS"
    maliewS.vm.network "private_network", ip: "192.168.56.110"

    # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
    maliewS.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "maliewS"]
      v.memory = 1024
      v.cpus = 1
    end

    # https://developer.hashicorp.com/vagrant/docs/provisioning/shell
    maliewS.vm.provision "shell", path: "scripts/install-k3s-server.sh"
  end

  config.vm.define "maliewSW" do |maliewSW|
    maliewSW.vm.hostname = "maliewSW"
    maliewSW.vm.network "private_network", ip: "192.168.56.111"

    maliewSW.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "maliewSW"]
      v.memory = 1024
      v.cpus = 1
    end

    maliewSW.vm.provision "shell", path: "scripts/install-k3s-agent.sh"
  end
end
